//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empreendimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empreendimento()
        {
            this.Bloco = new HashSet<Bloco>();
            this.Unidade = new HashSet<Unidade>();
        }
    
        public long id { get; set; }
        public string nome { get; set; }
        public System.DateTime dataInicio { get; set; }
        public System.DateTime dataConclusao { get; set; }
        public int idTipo_Empreendimento { get; set; }
        public string endereco { get; set; }
        public double area_total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bloco> Bloco { get; set; }
        public virtual Tipo_Empreendimento Tipo_Empreendimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Unidade> Unidade { get; set; }
    }
}
